// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DiskErrorInfo disk error info
//
// swagger:model disk_error_info
type DiskErrorInfo struct {

	// The message and code detailing the error state of this disk.
	Reason *Error `json:"reason,omitempty"`

	// Disk error type.
	// Example: notallflashdisk
	// Read Only: true
	// Enum: ["onepath","onedomain","control","foreign","toobig","toosmall","invalidblocksize","targetasymmap","deviceassymmap","failovermisconfig","unknown","netapp","fwdownrev","qualfail","diskfail","notallflashdisk"]
	Type *string `json:"type,omitempty"`
}

// Validate validates this disk error info
func (m *DiskErrorInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReason(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DiskErrorInfo) validateReason(formats strfmt.Registry) error {
	if swag.IsZero(m.Reason) { // not required
		return nil
	}

	if m.Reason != nil {
		if err := m.Reason.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("reason")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("reason")
			}
			return err
		}
	}

	return nil
}

var diskErrorInfoTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["onepath","onedomain","control","foreign","toobig","toosmall","invalidblocksize","targetasymmap","deviceassymmap","failovermisconfig","unknown","netapp","fwdownrev","qualfail","diskfail","notallflashdisk"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		diskErrorInfoTypeTypePropEnum = append(diskErrorInfoTypeTypePropEnum, v)
	}
}

const (

	// DiskErrorInfoTypeOnepath captures enum value "onepath"
	DiskErrorInfoTypeOnepath string = "onepath"

	// DiskErrorInfoTypeOnedomain captures enum value "onedomain"
	DiskErrorInfoTypeOnedomain string = "onedomain"

	// DiskErrorInfoTypeControl captures enum value "control"
	DiskErrorInfoTypeControl string = "control"

	// DiskErrorInfoTypeForeign captures enum value "foreign"
	DiskErrorInfoTypeForeign string = "foreign"

	// DiskErrorInfoTypeToobig captures enum value "toobig"
	DiskErrorInfoTypeToobig string = "toobig"

	// DiskErrorInfoTypeToosmall captures enum value "toosmall"
	DiskErrorInfoTypeToosmall string = "toosmall"

	// DiskErrorInfoTypeInvalidblocksize captures enum value "invalidblocksize"
	DiskErrorInfoTypeInvalidblocksize string = "invalidblocksize"

	// DiskErrorInfoTypeTargetasymmap captures enum value "targetasymmap"
	DiskErrorInfoTypeTargetasymmap string = "targetasymmap"

	// DiskErrorInfoTypeDeviceassymmap captures enum value "deviceassymmap"
	DiskErrorInfoTypeDeviceassymmap string = "deviceassymmap"

	// DiskErrorInfoTypeFailovermisconfig captures enum value "failovermisconfig"
	DiskErrorInfoTypeFailovermisconfig string = "failovermisconfig"

	// DiskErrorInfoTypeUnknown captures enum value "unknown"
	DiskErrorInfoTypeUnknown string = "unknown"

	// DiskErrorInfoTypeNetapp captures enum value "netapp"
	DiskErrorInfoTypeNetapp string = "netapp"

	// DiskErrorInfoTypeFwdownrev captures enum value "fwdownrev"
	DiskErrorInfoTypeFwdownrev string = "fwdownrev"

	// DiskErrorInfoTypeQualfail captures enum value "qualfail"
	DiskErrorInfoTypeQualfail string = "qualfail"

	// DiskErrorInfoTypeDiskfail captures enum value "diskfail"
	DiskErrorInfoTypeDiskfail string = "diskfail"

	// DiskErrorInfoTypeNotallflashdisk captures enum value "notallflashdisk"
	DiskErrorInfoTypeNotallflashdisk string = "notallflashdisk"
)

// prop value enum
func (m *DiskErrorInfo) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, diskErrorInfoTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DiskErrorInfo) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this disk error info based on the context it is used
func (m *DiskErrorInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateReason(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DiskErrorInfo) contextValidateReason(ctx context.Context, formats strfmt.Registry) error {

	if m.Reason != nil {

		if swag.IsZero(m.Reason) { // not required
			return nil
		}

		if err := m.Reason.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("reason")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("reason")
			}
			return err
		}
	}

	return nil
}

func (m *DiskErrorInfo) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DiskErrorInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DiskErrorInfo) UnmarshalBinary(b []byte) error {
	var res DiskErrorInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
